version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - mvn --version
  build:
    commands:
      - echo Building the Spring Boot application...
      - mvn package -DskipTests
artifacts:
  files:
    - target/*.jar
