version: 0.2

phases:
  pre_build:
    commands:
      - echo "Build (if needed) and search for JAR"
      - mvn clean package -DskipTests || echo "Skipping build, no Maven project"
      - JAR_PATH=$(find . -type f -name "*.jar" | head -n 1)
      - echo "Will deploy JAR at path: $JAR_PATH"
  build:
    commands:
      - mkdir deploy
      - cp "$JAR_PATH" deploy/application.jar
      - cd deploy
      - zip ../app-deploy.zip application.jar
artifacts:
  files:
    - app-deploy.zip
