version: 0.2
phases:
  build:
    commands:

      # ToDoList build commands
      - cd toDoList
      - mvn clean install -DskipTests

artifacts:
  files:

    # ToDoList artifact
    - toDoList/target/*.jar
  discard-paths: yes

  # Editing project
