version: 0.2

phases:
  build:
    commands:
      # Build ToDoList Spring Boot app
      - cd toDoList
      - mvn clean install -DskipTests
      - cd ..

      # Prepare Elastic Beanstalk deployment bundle
      - mkdir deploy
      - cp toDoList/target/*.jar deploy/application.jar
      - cd deploy
      - zip ../app-deploy.zip application.jar
      - cd ..

artifacts:
  files:
    # EB deployment ZIP
    - app-deploy.zip
  discard-paths: yes
